with open("schedule.txt", "r+") as myfile:
	data = [s.strip() for s in myfile.read().splitlines()]

	for item in data:
		print 'perfArtists.add("' + item + '");'

perfArtists.add("LCD SOUNDSYSTEM");
perfArtists.add("J. COLE");
perfArtists.add("DURAN DURAN");
perfArtists.add("BEACH HOUSE");
perfArtists.add("GRIMES");
perfArtists.add("MIIKE SNOW");
perfArtists.add("NATHANIEL RATELIFF & THE NIGHT SWEATS");
perfArtists.add("THOMAS JACK");
perfArtists.add("FOALS");
perfArtists.add("THE CLAYPOOL LENNON DELIRIUM");
perfArtists.add("ST. LUCIA");
perfArtists.add("POLIÇA");
perfArtists.add("HIATUS KAIYOTE");
perfArtists.add("RA RA RIOT");
perfArtists.add("TOKIMONSTA");
perfArtists.add("WET");
perfArtists.add("JIDENNA");
perfArtists.add("LÅPSLEY");
perfArtists.add("MARIAN HILL");
perfArtists.add("CAVEMAN");
perfArtists.add("VULFPECK");
perfArtists.add("MOON TAXI");
perfArtists.add("LANY");
perfArtists.add("WHITNEY");
perfArtists.add("REDLIGHT");
perfArtists.add("PILLOWTALK");
perfArtists.add("FDVM");
perfArtists.add("219 BOYS");
perfArtists.add("MAKE IT FUNKY DJS");
perfArtists.add("RADIOHEAD");
perfArtists.add("ZEDD");
perfArtists.add("AIR");
perfArtists.add("SUFJAN STEVENS");
perfArtists.add("HALSEY");
perfArtists.add("BIG GRAMS (BIG BOI + PHANTOGRAM)");
perfArtists.add("THE LAST SHADOW PUPPETS");
perfArtists.add("LORD HURON");
perfArtists.add("JAUZ");
perfArtists.add("VINCE STAPLES");
perfArtists.add("YEARS & YEARS");
perfArtists.add("IBEYI");
perfArtists.add("PEACHES");
perfArtists.add("ANDERSON .PAAK & THE FREE NATIONALS");
perfArtists.add("THE WOMBATS");
perfArtists.add("THE KNOCKS");
perfArtists.add("ROGUE WAVE");
perfArtists.add("CON BRIO");
perfArtists.add("KEVIN MORBY");
perfArtists.add("FANTASTIC NEGRITO");
perfArtists.add("LEWIS DEL MAR");
perfArtists.add("JULIEN BAKER");
perfArtists.add("DECLAN MCKENNA");
perfArtists.add("METHYL ETHEL");
perfArtists.add("VICTOR CALDERONE");
perfArtists.add("PURPLE DISCO MACHINE");
perfArtists.add("TRANSLUCENT");
perfArtists.add("W.HAZE");
perfArtists.add("MOTION POTION");
perfArtists.add("LIONEL RICHIE");
perfArtists.add("LANA DEL REY");
perfArtists.add("MAJOR LAZER");
perfArtists.add("RYAN ADAMS AND THE SHINING");
perfArtists.add("CHANCE THE RAPPER");
perfArtists.add("MIGUEL");
perfArtists.add("JASON ISBELL");
perfArtists.add("THIRD EYE BLIND");
perfArtists.add("KEHLANI");
perfArtists.add("GRIZ");
perfArtists.add("BRANDI CARLILE");
perfArtists.add("SNAKEHIPS");
perfArtists.add("LETTUCE");
perfArtists.add("OH WONDER");
perfArtists.add("KAMASI WASHINGTON");
perfArtists.add("JACK GARRATT");
perfArtists.add("RÜFÜS DU SOL");
perfArtists.add("DIIV");
perfArtists.add("NATALIA LAFOURCADE");
perfArtists.add("THE OH HELLOS");
perfArtists.add("FRANCES");
perfArtists.add("HÆLOS");
perfArtists.add("CLOVES");
perfArtists.add("HERON OBLIVION");
perfArtists.add("GINA TURNER");
perfArtists.add("LEE K");
perfArtists.add("GRENSTA");
perfArtists.add("DECKARD");
perfArtists.add("DEREK HENA");