# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

source 'https://github.com/CocoaPods/Specs.git'

target 'Outside Recs' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Outside Recs
  pod 'Material', '~> 1.0'
  pod 'SnapKit'
  pod 'SVProgressHUD'
  pod 'Alamofire', '~> 3.4'

  target 'Outside RecsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Outside RecsUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
